angular.module('tera').controller('translateCtrl', ['$translate', '$scope', function ($translate, $scope) {

  $scope.changeLanguage = function (langKey) {
    $translate.use(langKey);
  };

}]);

angular.module('tera').config(['$translateProvider', function ($translateProvider) {
  $translateProvider.useSanitizeValueStrategy('escape');

  $translateProvider.translations('en', {

    // Navigation
    'About': 'About',
    'Setup': 'Setup',
    'Requirements': 'Requirements',
    'Dungeons': 'Dungeons',
    'Servers': 'Servers',
    'Classes': 'Classes',
    'Premium': 'GO PREMIUM!',
    'MeterInfo': 'Get Meter Info',
    'Logo': 'Realtime DPS Visualization & Tracking For Tera Online',

    // Home Page / Ranking Pages
    'WhatIsTeraDps': 'What is TeraDPS?',
    'WhatIsTeraDps2': 'TeraDPS is a web application that was created to allow players to share dps meter data with other people and improve themselves by comparing and analyzing it.',

    'RegionParty': 'Region & Party',
    'Name': 'Name',
    'Class': 'Class',
    'Server': 'Server',
    'Boss': 'Boss',
    'DPS': 'DPS',
    'Date': 'Date',

    // Ranking
    'Players': '',
    'Regions': '',
    'NA': 'North America',
    'EU': 'Europe',
    'RU': 'Russia',
    'KR': 'Korea',
    'JP': 'Japan',
    'TW': 'Taiwan',
    'HealerComp': 'Healer Comp',
    'All': 'All',
    'SearchSave': 'Search & Save Settings',
    'TANK': 'TANK',

    // Details
    'StanceConsumable': 'Stances & Consumables Used',
    'Crit': 'Crit',
    'Total': '',
    'Debuff': '',
    'Uptime': '',
    'FightDuration': '',
    'Party DPS': 'Party DPS',
    'SubmittedOn': 'Submitted On',
    'SubmittedBy': 'Submitted By',

    // Enrage (Example: X was enraged for 50% of the fight.)
    'WasEnragedFor': 'was enraged for',
    'OfTheFight': 'of the fight',

    // Skill Breakdowns
    'Skill': '',
    'Hits': '',
    'TotalDamage': 'Total Damage',
    'CritRate': '',
    'TotalPercent': 'Total Percent',
    'HighestCrit': '',
    'AverageCrit': '',
    'AverageWhite': '',
    'Buff': '',

    // Deathes (Example: X died 2 times, and spent 9% of the fight on the floor.)
    'Death1': 'died',
    'Death2': 'times, and spent ',
    'Death3': 'of the fight on the floor.',

    // About Page
    'WhatIs': '',
    'WhatIs2': '',
    'Meet': '',
    'NickBio': '',
    'NeowutranBio': '',
    'GioBio': '',
    'YuraiBio': '',

    // Setup Page
    'SetupStart': '',
    'SetupStart2': '',
    'Choose': '',
    'Shinra': '',
    'Casual': '',
    'MainSetup': '',
    'ShinraSetup': '',
    'CasualSetup': '',
    'AllDone': '',
    'AllDoneGuide': '',

    // Shinra Guide
    'ShinraIntro': '',
    'ShinraOne': '',
    'ShinraOneGuide': '',
    'ShinraTwo': '',
    'ShinraTwoGuide': '',
    'ShinraTwoGuide2': '',
    'ShinraThree': '',
    'ShinraThreeGuide': '',
    'ShinraThreeGuide2': '',
    'ShinraThreeGuide3': '',
    'ShinraFour': '',
    'ShinraFourGuide': '',

    // Casual Guide
    'CasualIntro': '',
    'CasualOne': '',
    'CasualOneGuide': '',
    'CasualTwo': '',
    'CasualTwoGuide': '',
    'CasualTwoGuide2': '',
    'CasualThree': '',
    'CasualThreeGuide': '',
    'CasualThreeGuide2': '',
    'CasualFour': '',
    'CasualFourGuide': '',
    'CasualFourGuide2': '',
    'CasualFourGuide3': '',
    'CasualFive': '',
    'CasualFiveGuide': '',

    // Requirements
    'SubReqs': '',
    'SubReqsIntro': '',
    'Expires': '',
    'AcceptedServers': '',
    'AcceptedServersBody': '',
    'BannedConsumables': '',
    'BannedConsumablesBody': '',
    'BanCon1': '',
    'BanCon1Desc': '',
    'BanCon2': '',
    'BanCon2Desc': '',
    'BanCon3': '',
    'BanCon3Desc': '',
    'BanCon4': '',
    'BanCon4Desc': '',
    'AcceptedBosses': '',
    'AcceptedBossesBody': '',
    'ThatsIt': '',

    // Premium
    'PremiumIsHere': '',
    'PremiumIsHereBody': '',
    'PriceFeatures': '',
    'PriceFeatureBody': '',
    'PermRank': '',
    'PermRankBody': '',
    'PremIcon': '',
    'PremIconBody': '',
    'UserPro': '',
    'UserProBody': '',
    'PriceFeatureBody2': '',
    'HowTo': '',
    'HowToBody': '',
    'HowToBody2': '',
    'PaypalTransId': '',
    'PaypalTransIdBody': '',
    'CharacterName': '',
    'CharacterNameBody': '',
    'ServerNameBody': '',
    'TeraDpsUser': '',
    'TeraDpsUserClick': '',
    'HowToBody3': '',
    'ThankYouForSupport': '',

    // Retrieve Meter Info
    'RetrieveKeys': '',
    'RetrieveKeyBody': '',
    'Email': '',
    'Password': '',
    'RejectedReq': '',
    'UserId': '',
    'AuthToken': '',
    'Close': '',

    "NotSpecified": "Not Specified",
    "Keen": "Keen Etching",
    "Pumped": "Pumped Etching",
    "Energetic": "Energetic Etching",
    "Grounded": "Grounded Etching",
    "Unyielding": "Unyielding Etching",
    "Relentless": "Relentless Etching",
    "Enrage": "Increases damage by 9.3% when attacking enraged monsters.",
    "Flat": "Increases damage by 6%.",
    "Behind": "Increases damage by 6.9% when attacking from behind.",
    "HighestAggro": "Increases damage by 8.6% to the target with the most aggro toward you.",
    "Cooldown": "Decreases skill cooldowns by 7.2%.",
    "Aspd": "Increases Attack Speed by 4.5%.",
    "CritRate": "Increases Crit Factor by 14.",
    "CritPower": "Increases Crit Power by 0.3.",
    "KnockedDmg": "Increases damage by 5.3% when attacking knocked-down targets.",
    "MpCombatStart": "0.5% chance to replenish MP when combat starts.",
    "MpSkill": "Replenishes 0.6% of total MP instantly when you use a skill.",
    "AspdBase": "Increases Attack Speed by 9%.",
    "CritRateBase": "Increases Crit Factor by 18.",
    "EnrageArmor": "Decreases damage from enraged monsters by 10%.",
    "FlatArmor": "Decreases damage taken by 6%.",
    "FrontalArmor": "Decreases damage taken from frontal attacks by 6.9%.",
    "HighestAggroArmor": "Decreases damage by 8.7% from the monster with the most aggro toward you.",
    "MaxHpArmor": "Raises max HP by 8%.",
    "HpResArmor": "Healing skills affecting you increase by 6%.",

      "SpringAtkRoll": "Increases damage of Spring Attack by 15%.",
      "OnslaughtRoll": "Increases damage of Onslaught by 15%.",
      "OnslaughtRoll2": "Replenishes 50 MP when Onslaught skill hits target.",
      "PledgeRoll": "Replenishes 75 MP upon using Pledge of Protection.",
      "ShieldBashRoll": "Decreases cooldown of Shield Bash by 10%.",
      "ShoutRoll": "Decreases cooldown of Challenging Shout by 10%.",
      "CounterRoll": "Increases damage of Shield Counter by 17%.",
      "CounterRoll2": "Decreases cooldown of Shield Counter by 10%.",
      "LeashRoll": "Replenishes 50 MP when Leash skill hits target.",
      "SecondWindRoll": "Decreases cooldown of Second Wind by 10%.",

      "PunchRoll": "Increases damage of Punch by 15%.",
      "DivineWrathRoll": "Decreases cooldown of Divine Wrath by 10%.",
      "JackhammerRoll": "Increases damage of Jackhammer by 12%.",
      "JackhammerRoll2": "Replenishes 30 MP when Jackhammer hits a target.",
      "RoundhouseRoll": "Decreases cooldown of Roundhouse Kick by 15%.",
      "PiledriverRoll": "Increases damage of Piledriver by 12%.",
      "GroundPoundRoll": "Increases damage of Ground Pounder by 10%.",
      "RampageRoll": "Generates 2% Rage when Rampage hits a target.",
      "MeatGrinderRoll": "Doubles the chance to crit when using Meat Grinder.",
      "RageRoll": "Reduces Rage cost of Invigorating Rage by 600.",

      "BladeDrawRoll": "Increases damage of Blade Draw by 10%.",
      "BladeDrawRoll2": "Decreases cooldown of Blade Draw by 10%.",
      "RainOfBlowsRoll": "Increases damage of Rain of Blows by 12%.",
      "TorrentRoll": "Replenishes 50 MP when Torrent of Blows skill hits target.",
      "DeathFromAboveRoll": "Decreases cooldown of Death From Above by 10%.",
      "VortexRoll": "Increases damage of Vortex Slash by 12%.",
      "RisingFuryRoll": "Increases damage of Rising Fury by 12%.",
      "PounceRoll": "Replenishes 50 MP when Pounce skill hits target.",
      "BattleCryRoll": "Decreases cooldown of Battle Cry by 12%.",

      "OverhandRoll": "Increases damage of Overhand Strike by 10%.",
      "KnockdownRoll": "Replenishes 40 MP when Knockdown Strike skill hits target.",
      "WhirlwindRoll": "Increases damage of Whirlwind by 10%.",
      "EvasiveRoll": "Decreases cooldown of Evasive Roll by 10%.",
      "BackstabRoll": "Decreases cooldown of Backstab by 5%.",
      "TriumphRoll": "Increases duration of Triumphant Shout effect by 20%.",
      "KickRoll": "Decreases cooldown of Startling Kick by 10%.",
      "OverpowerRoll": "Decreases cooldown of Overpower by 12%.",
      "TenacityRoll": "Decreases cooldown of Tenacity by 10%.",
      "InColdBloodRoll": "Decreases cooldown of In Cold Blood by 15%.",

      "ThunderRoll": "Increases damage of Thunder Strike by 8%.",
      "CycloneRoll": "Increases damage of Cyclone by 8%.",
      "FlattenRoll": "Increases damage of Flatten by 10%.",
      "StaggerRoll": "Increases damage of Staggering Strike by 25%.",
      "TenacityRoll": "Decreases cooldown of Tenacity by 10%.",
      "TriumphRoll": "Increases duration of Triumphant Shout effect by 20%.",
      "LethalRoll": "Increases damage of Lethal Strike by 15%.",
      "FlurryRoll": "Increases duration of Flurry of Blows effect by 17%.",
      "DoomRoll": "Decreases cooldown of Inescapable Doom by 5%.",
      "DoomRoll2": "Replenishes 60 MP when Inescapable Doom skill hits target.",

      "RadiantRoll": "Increases damage of Radiant Arrow by 10%.",
      "PenetratingRoll": "Increases damage of Penetrating Arrow by 10%.",
      "VolleyRoll": "Increases damage of Arrow Volley by 15%.",
      "RainRoll": "Increases damage of Rain of Arrows by 10%.",
      "RainRoll2": "Decreases cooldown of Rain of Arrows by 10%.",
      "StunTrapRoll": "Decreases cooldown of Stunning Trap by 15%.",
      "CloseRoll": "Increases duration of Close Quarters effect by 5%.",
      "PoisonRoll": "Increases duration of Poison Arrow effect by 17%.",
      "BreakawayRoll": "Decreases cooldown of Breakaway Bolt by 12%.",
      "VelikRoll": "Replenishes 50 MP when Velik's Mark skill hits target. ",

      "ShearRoll": "Increases skill damage of Double Shear by 10%.",
      "ShearRoll2": "Decreases cooldown of Double Shear by 10%.",
      "GrimRoll": "Increases skill damage of Grim Strike by 12%.",
      "SpiralRoll": "Replenishes 20 MP when Death Spiral skill hits target.",
      "ShadowStepRoll": "Decreases cooldown of Shadow Step by 10%.",
      "SmiteRoll": "Decreases cooldown of Smite by 10%.",
      "BarrageRoll": "Increases skill damage of Spiral Barrage by 15%.",
      "ShadowBurstRoll": "Increases skill damage of Shadow Burst by 10%.",
      "ShadowLashRoll": "Replenishes 20 MP when Shadow Lash skill hits target.",
      "SoulReversalRoll": "Decreases cooldown of Soul Reversal by 15%.",

      "FireblastRoll": "Increases damage of Fireblast by 10%.",
      "VoidPulseRoll": "Increases damage of Void Pulse by 10%.",
      "HailStormRoll": "Increases damage of Hail Storm by 10%.",
      "ManaInfuseRoll": "Increases MP replenished by Mana Infusion by 12%.",
      "ManaSiphonRoll": "Increases MP replenished by Mana Siphon by 17%.",
      "FlamingBarrageRoll": "Increases damage of Flaming Barrage by 15%.",
      "GlacialRoll": "Decreases cooldown of Glacial Retreat by 10%.",
      "JauntRollSorc": "Decreases cooldown of Teleport Jaunt by 10%.",
      "ManaBarrierRoll": "Decreases cooldown of Mana Barrier by 15%.",
      "BackstepRoll": "Decreases cooldown of Backstep by 10%.",

      "BlastRoll": "Increases skill damage of Blast by 15%.",
      "BombardRoll": "Decreases cooldown of Bombardment by 8%.",
      "ScatterRoll": "Increases skill damage of Scattershot by 10%.",
      "ScatterRoll2": "Replenishes 150 MP when Scattershot hits a target.",
      "PointBlankRoll": "Decreases cooldown of Point Blank by 15%.",
      "BurstFireRoll": "Reduces Willpower cost of Burst Fire by 5.",
      "ArcaneRoll": "Increases skill damage of Arcane Barrage by 7%.",
      "RocketRoll": "Decreases cooldown of Rocket Jump by 10%.",
      "ArcRoll": "Increases duration of Arc Bomb by 20%.",
      "ReplenishRoll": "Decreases cooldown of Replenishment by 15%.",

      "DoubleCutRoll": "Increases skill damage of Double Cut by 12%.",
      "DecoyRoll": "Decreases cooldown of Decoy Jutsu by 10%.",
      "SkyfallRoll": "Increases skill damage of Skyfall by 10%.",
      "LeavesRoll": "Replenishes 30 MP when Leaves on the Wind hits a target.",
      "DeathBlossomRoll": "Decreases cooldown of Death Blossom by 15%.",
      "CircleRoll": "Increases skill damage of Circle of Steel by 10%.",
      "OneThousandRoll": "Increases skill damage of One Thousand Cuts by 12%.",
      "JaggedRoll": "Generates 2% Chi when Jagged Path hits a target.",
      "ImpactRoll": "Doubles the chance to crit of Impact Bomb.",
      "FireAvalancheRoll": "Decreases cooldown of Fire Avalanche by 15%.",

      "FocusRoll": "Increases healing of Focus Heal by 15%.",
      "RegenRoll": "Increases duration effect of Regeneration Circle by 10%.",
      "HealingRoll": "Increases healing of Healing Circle by 10%.",
      "ImplosionRoll": "Increases damage of Shocking Implosion by 15%.",
      "ImplosionRoll2": "Decreases cooldown of Shocking Implosion by 10%.",
      "RestorativeRoll": "Increases duration of Restorative Burst effect by 15%.",
      "KaiaRoll": "Decreases cooldown of Kaia's Shield by 10%.",
      "EnergyRoll": "Decreases cooldown of Energy Stars by 10%.",
      "ManaChargeRoll": "Increases charging speed of Mana Charge by 15%.",
      "FieryRoll": "Decreases cooldown of Fiery Escape by 15%.",

      "JauntRollMys": "Decreases cooldown of Teleport Jaunt by 7%.",
      "MireRoll": "Replenishes 100 MP when Mire skill hits target.",
      "SharaRoll": "Decreases cooldown of Shara's Lash by 10%.",
      "VowRoll": "Replenishes 175 MP when Vow of Rebirth skill hits target.",
      "MetaRoll": "Increases damage of Metamorphic Smite by 17%.",
      "CurseRoll": "Increases duration of Volley of Curses effect by 15%.",
      "SonorousRoll": "Replenishes 110 MP when Sonorous Dreams skill hits target.",
      "ProtectionRoll": "Replenishes 175 MP when casting Thrall of Protection.",
      "LifeRoll": "Replenishes 175 MP when casting Thrall of Life."

  });

  $translateProvider.translations('ru', {

    // Navigation
    'About': '',
    'Setup': '',
    'Requirements': '',
    'Dungeons': '',
    'Servers': '',
    'Classes': '',
    'Premium': '',
    'MeterInfo': '',
    'Logo': '',

    // Home Page / Ranking Pages
    'WhatIsTeraDps': '',
    'WhatIsTeraDps2': '',

    'RegionParty': '',
    'Name': '',
    'Class': '',
    'Server': '',
    'Boss': '',
    'DPS': '',
    'TANK': '',
    'Date': '',

    // Ranking
    'Players': '',
    'Regions': '',
    'NA': '',
    'EU': '',
    'RU': '',
    'KR': '',
    'JP': '',
    'TW': '',
    'HealerComp': '',
    'All': '',
    'SearchSave': '',

    // Details
    'StanceConsumable': '',
    'Crit': '',
    'Total': '',
    'Debuff': '',
    'Uptime': '',
    'FightDuration': '',
    'Party DPS': '',
    'SubmittedOn': '',
    'SubmittedBy': '',

    // Enrage (Example: X was enraged for 50% of the fight.)
    'WasEnragedFor': 'was enraged for',
    'OfTheFight': 'of the fight',

    // Skill Breakdowns
    'Skill': '',
    'Hits': '',
    'TotalDamage': '',
    'CritRate': '',
    'TotalPercent': '',
    'HighestCrit': '',
    'AverageCrit': '',
    'AverageWhite': '',
    'Buff': '',

    // Deathes (Example: X died 2 times, and spent 9% of the fight on the floor.)
    'Death1': 'died',
    'Death2': 'times, and spent ',
    'Death3': 'of the fight on the floor.',

    // About Page
    'WhatIs': '',
    'WhatIs2': '',
    'Meet': '',
    'NickBio': '',
    'NeowutranBio': '',
    'GioBio': '',
    'YuraiBio': '',

    // Setup Page
    'SetupStart': '',
    'SetupStart2': '',
    'Choose': '',
    'Shinra': '',
    'Casual': '',
    'MainSetup': '',
    'ShinraSetup': '',
    'CasualSetup': '',
    'AllDone': '',
    'AllDoneGuide': '',

    // Shinra Guide
    'ShinraIntro': '',
    'ShinraOne': '',
    'ShinraOneGuide': '',
    'ShinraTwo': '',
    'ShinraTwoGuide': '',
    'ShinraTwoGuide2': '',
    'ShinraThree': '',
    'ShinraThreeGuide': '',
    'ShinraThreeGuide2': '',
    'ShinraThreeGuide3': '',
    'ShinraFour': '',
    'ShinraFourGuide': '',

    // Casual Guide
    'CasualIntro': '',
    'CasualOne': '',
    'CasualOneGuide': '',
    'CasualTwo': '',
    'CasualTwoGuide': '',
    'CasualTwoGuide2': '',
    'CasualThree': '',
    'CasualThreeGuide': '',
    'CasualThreeGuide2': '',
    'CasualFour': '',
    'CasualFourGuide': '',
    'CasualFourGuide2': '',
    'CasualFourGuide3': '',
    'CasualFive': '',
    'CasualFiveGuide': '',

    // Requirements
    'SubReqs': '',
    'SubReqsIntro': '',
    'Expires': '',
    'AcceptedServers': '',
    'AcceptedServersBody': '',
    'BannedConsumables': '',
    'BannedConsumablesBody': '',
    'BanCon1': '',
    'BanCon1Desc': '',
    'BanCon2': '',
    'BanCon2Desc': '',
    'BanCon3': '',
    'BanCon3Desc': '',
    'BanCon4': '',
    'BanCon4Desc': '',
    'AcceptedBosses': '',
    'AcceptedBossesBody': '',
    'ThatsIt': '',

    // Premium
    'PremiumIsHere': '',
    'PremiumIsHereBody': '',
    'PriceFeatures': '',
    'PriceFeatureBody': '',
    'PermRank': '',
    'PermRankBody': '',
    'PremIcon': '',
    'PremIconBody': '',
    'UserPro': '',
    'UserProBody': '',
    'PriceFeatureBody2': '',
    'HowTo': '',
    'HowToBody': '',
    'HowToBody2': '',
    'PaypalTransId': '',
    'PaypalTransIdBody': '',
    'CharacterName': '',
    'CharacterNameBody': '',
    'ServerNameBody': '',
    'TeraDpsUser': '',
    'TeraDpsUserClick': '',
    'HowToBody3': '',
    'ThankYouForSupport': '',

    // Retrieve Meter Info
    'RetrieveKeys': '',
    'RetrieveKeyBody': '',
    'Email': '',
    'Password': '',
    'RejectedReq': '',
    'UserId': '',
    'AuthToken': '',
    'Close': '',

  });

  $translateProvider.preferredLanguage('en');
}]);
